target 'HomeCooked' do
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'SwiftyJSON'

  target 'HomeCookedTests' do
    pod 'Firebase'
    pod 'SwiftyJSON'
  end
end
